packages:
  - "packages/lixpi/capability-system"
  - "packages/lixpi/canvas-engine"
  - "packages/lixpi/canvas-components"
  - "packages/lixpi/canvas-components-lixpi-specific"
  - "packages/lixpi/constants/ts"
  - "packages/lixpi/debug-tools/ts"
  - "packages/lixpi/nats-service/ts"
  - "packages/lixpi/prosemirror"
  - "packages/lixpi/test-utils"
  - "packages/lixpi/ui-kit"
  - "packages/lixpi/ui-primitives"
  - "packages/lixpi/auth-client"
  - "packages/lixpi/web-client-service-factory"

allowBuilds:
  "@parcel/watcher": true
  browser-tabs-lock: true
  esbuild: true
